CREATE DATABASE PruebaTecnica

	CREATE TABLE EMPLEADO ( 
	ID INT PRIMARY KEY, 
	NOMBRE VARCHAR(50),
	APELLIDO VARCHAR(59),
	SEXO CHAR(1), 
	FECHA_NACIMIENTO DATE,
	SALARIO INT
	)


	CREATE TABLE VACACIONES( 
	ID_VACACIONES INT PRIMARY KEY, 
	FK_ID_EMPLE INT FOREIGN KEY REFERENCES EMPLEADO(ID),
	FECHA_INICIO DATE,
	FECHA_FIN DATE, 
	ESTADO CHAR(1), 
	CANTIDAD_DIAS INT
	)

	/*EN ESTA TABLA SE ALMACENA LA INFORMACIÓN BASICA DE LOS EMPLEAD*/

	/*EN ESTA TABLA SE ALMACENA LA INFORMACIÓN BASICA DE LOS EMPLEADOS*/ 
	INSERT INTO EMPLEADO VALUES (1,'JUAN','PELAEZ','M','1985-01- 29',3500000); 
	INSERT INTO EMPLEADO VALUES (2,'ANDRES','GARCIA','M','1975-05- 22',5500000); 
	INSERT INTO EMPLEADO VALUES (3,'LAURA','PEREZ','F','1991-09- 10',2500000);
	INSERT INTO EMPLEADO VALUES (4,'PEPE','MARTINEZ','M','1987-12- 01',3800000);
	INSERT INTO EMPLEADO VALUES (5,'MARGARITA','CORRALES','F','1990- 07-02',4500000);


	/*EN ESTA TABLA SE ALMACENA LAS SOLCITUDES DE VACIONES DE CADA EMPLEADO*/
	INSERT INTO VACACIONES VALUES (1,1,'2019-07-01','2019-07-15','A',14); 
	INSERT INTO VACACIONES VALUES (2,2,'2019-03-01','2019-03-15','R',14); 
	INSERT INTO VACACIONES VALUES (3,2,'2019-04-01','2019-04-15','A',14); 
	INSERT INTO VACACIONES VALUES (4,2,'2019-08-14','2019-08-20','A',6);
	INSERT INTO VACACIONES VALUES (5,3,'2019-08-20','2019-08-25','A',5); 
	INSERT INTO VACACIONES VALUES (6,3,'2019-12-20','2019-12-31','A',11)

	/*MOSTRAR TODA LA TABLA*/
	SELECT * FROM EMPLEADO
	SELECT * FROM VACACIONES
	 
	/*PRIMER PUNTO, SELECCIONE NOMBRE, APELLIDO, SALARIO*/
	 SELECT nombre, apellido,salario FROM EMPLEADO

	 /*2 SELECCIONE EL NOMBRE, APELLIDO Y SALARIO DE TODOS LOS EMPLEADOS QUE GANEN MAS DE 4 MILLONES*/
	 SELECT NOMBRE,APELLIDO,SALARIO FROM EMPLEADO
	 WHERE SALARIO > 4000000
	 
	 /*3CUANTOS EMPLEADOS HAT DEL GENERO M Y CUANTOS DEL F */
	 SELECT COUNT(SEXO) AS sexoF FROM EMPLEADO WHERE SEXO = 'F'
	 SELECT COUNT(SEXO) AS sexoM FROM EMPLEADO WHERE SEXO = 'M'

	 SELECT SEXO,COUNT(*) AS CANTIDAD FROM EMPLEADO
	 GROUP BY SEXO

	 /* 4.SELECCION DE LOS EMPLEADOS QUE NO HAN ECHO UNA SALICITUD DE VACACIONES*/
	 SELECT * FROM EMPLEADO
	 SELECT * FROM VACACIONES

	 SELECT NOMBRE FROM EMPLEADO
	 FULL JOIN VACACIONES ON ID=FK_ID_EMPLE
	 WHERE ID_VACACIONES IS NULL

	 /*5. SELECCCIONE LOS EMPLEADOS QUE TENGAN MAS DE UNA SALICITUD DE VACACIONES Y MUESTRE CUANTOS TIENEN LOS QUE CUMPLEN*/
	 SELECT NOMBRE,COUNT(*) as CANTIDADSOLICITUDES FROM EMPLEADO
	 INNER JOIN VACACIONES ON ID=FK_ID_EMPLE
	 GROUP BY NOMBRE
	 HAVING COUNT(*) >1

	 /*DETERMINE EL SALARIO PROMEDIO DE LOS EMPLEADOS*/
	 SELECT AVG(SALARIO) AS PROMEDIO FROM EMPLEADO
	 

	 /*DETERMINE LA CANTIDAD DE DIAS ´PROMEDIO SOLICITADOS DE VACACIONES POR CADA EMPLEADO*/
	 SELECT NOMBRE,AVG(CANTIDAD_DIAS) AS SUMA FROM EMPLEADO
	 INNER JOIN VACACIONES ON ID=FK_ID_EMPLE
	 GROUP BY NOMBRE

	 /* SELECCIONE EL EMPLEO QUE MAYOR CANTIDAD DE DIAS DE VACACIONES HA SOLICITADO, MUESTRE EL NOMBRE, APELLIDO Y CANTIDAD*/
	 /*DE DIAS TOTALES SOLICITADOS*/
	 SELECT TOP 1 NOMBRE,SUM(CANTIDAD_DIAS) AS SUMA FROM EMPLEADO
	 INNER JOIN VACACIONES ON ID=FK_ID_EMPLE
	 GROUP BY NOMBRE
	 ORDER BY SUMA DESC

	 /*MUESTRE LA CANTIDAD DE DIAS APROBADOS Y RECHAZADOS POR CADA EMPLEADO*/
	 SELECT NOMBRE,SUM(CANTIDAD_DIAS) AS CONTEO,ESTADO FROM EMPLEADO 
	 INNER JOIN VACACIONES ON ID = FK_ID_EMPLE
	GROUP BY NOMBRE, ESTADO
